

services:
  db:
    image: postgres:15-alpine
    container_name: rehab_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1488
      POSTGRES_DB: reability
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: